version: "3.8"
services:
  owncast:
    image: owncast/owncast:latest
    container_name: owncast
    ports:
      - "8083:8080"  # HTTP
      - "1937:1935"  # RTMP
    volumes:
      - ./owncast_data:/app/data
    environment:
      - OWNCAST_BIND=0.0.0.0
      - OWNCAST_HTTP_PORT=8083
      - OWNCAST_RTMP_PORT=1937
      - OWNCAST_SITE_TITLE=My Live Stream
      - OWNCAST_BASE_URL=https://onwcastservernow.apps.livelesson.name.ng
